pageTitle: 潘峰个人简历
name_cn: 潘峰
name_en: Power
jobTitle: 研发工程师
mobile: 137-6513-1032
mail: 0x208#f-tm.net
qq: 125-067-985
introduces:
  - 程序猿、伪极客，比较宅，兴趣爱好广泛，包括但不限于coding、hack、各种高科技、各种极客玩具等。
  - 时刻关注各种新技术，坚持不断学习，技术方面不限于前后端、架构、机器学习、安全等，学习能力、独立解决问题强，有强烈的责任感。
links:
  - icon: icon-github
    link: https://github.com/googlerobot

technologyStack:
  title: 技术能力
  icon: icon-link
  description:
    - 精通PHP及web前端开发，具备一定的系统架构设计能力，熟悉Linux、MySQL、Memcache/Redis等相关技术，熟悉Web安全，计算机基础知识扎实。



works:
  title: 工作经历
  icon: icon-experience
  list:
    - company: 美丽说
      job: 研发工程师
      date: 2014.8 - 至今
#      summary:
      projects:
        - date: 2015.5-至今
          content: 负责办公系统、财务系统等前端，带领2名RD完成各版本迭代，开发框架优化(代码模块化、模块跨项目复用、代码逻辑优化、性能优化，使页面毫秒级响应)，并建立前端开发规范、技术文档、体验一致的公共前端组件库（包括图标库、分页、时间轴、树形搜索下拉、通知提示、文件上传）等，提升前端开发效率，快速响应各部门需求.
        - date: 2015.2-2015.5
          content: 参与办公系统迁移，保证新旧系统稳定同步运行的情况下逐步迁移旧系统到SOA架构的API（新架构平均响应速度均在100ms以内并可对接任何系统和平台），独立完成其中多个模块的设计及开发，并对基础框架进行扩展及优化（参数自动过滤校验，SQL自动构造，统一认证的中间件，引入异常机制简化处理逻辑，任务队列处理耗时及离线任务，各种工具类），提升团队开发效率及系统安全性.
        - date: 2015.1-2015.2
          content: 独立开发舆情监控模块，通过python实时采集微博、资讯源、搜索引擎等与美丽说相关的数据进行情感分析（朴素贝叶斯分类器），将负面内容反馈给客服及时跟进,提升用户体验、公司的品牌形象.
        - date: 2014.8-2015.1
          content: 负责线上品牌活动，与运营沟通并根据需求开发相关功能，确保活动稳定进行以及活动数据收集，开发智能客服机器人相关接口（基于sphinx的知识库匹配）
    - company: 水果生鲜创业
      job: 技术负责人
      date: 2013.10 - 2014.8
      summary: 负责整个系统的设计开发、运维,参与了推广.
      projects:
        - date: 2014.4-2014.7
          content: 参与策划及产品推广
        - date: 2014.1-2014.4
          content: 开发H5及微信端,以及基于标签的推荐系统,根据用户的喜好及身体情况进行水果推荐.
        - date: 2013.10-2014.1
          content: 开发水果生鲜商城的PC端及管理后台

projects:
  title: 项目经验
  icon: icon-project
  list:
    - name: 导购项目
      description: 采集淘宝、京东、美丽说、蘑菇街等完整的商品信息及图文描述、SKU/属性、评论列表数据进行推广，靠SEO长尾关键词获取流量(http://www.shaojikuai.com)
    - name: 可视化数据抓取
      description: 基于CasperJS/PhantomJS的爬虫，通过浏览器插件提取特定站点的抓取规则，程序后台自动采集，抓取时根据规则自动提取链接、翻页等，实现了提取大量不同网站上相同结构的数据
